In [2]:
import math
import numpy as np
import transforms3d as tfs

In [4]:
theta = math.radians(45)
R_AB = np.array([math.cos(theta), -math.sin(theta), 0, math.sin(theta), math.cos(theta), 0, 0, 0, 1]).reshape(3, 3)
print(R_AB)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [7]:
print(tfs.quaternions.quat2mat([1,0,0,0]))
print(tfs.quaternions.mat2quat(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]])))
print(tfs.quaternions.quat2axangle([1,0,0,0]))
print(tfs.quaternions.axangle2quat([1,0,0],2*math.pi))
print(tfs.quaternions.quat2mat(tfs.quaternions.axangle2quat([1,0,0],2*math.pi)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0. 0.]
(array([1., 0., 0.]), 0.0)
[-1.0000000e+00  1.2246468e-16  0.0000000e+00  0.0000000e+00]
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  2.4492936e-16]
 [ 0.0000000e+00 -2.4492936e-16  1.0000000e+00]]


In [12]:
# 固定轴欧拉角转四元数
print(tfs.euler.euler2quat(2*math.pi,0,0,"sxyz"))
print(tfs.euler.euler2quat(0,0,0,"sxyz"))
# 四元数转固定轴欧拉角
print(tfs.euler.quat2euler([1,0,0,0],"sxyz"))
# 固定轴欧拉角转旋转矩阵
print(tfs.euler.euler2mat(0,0,0,"sxyz"))
# 旋转矩阵转固定轴欧拉角
print(tfs.euler.mat2euler(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]),"sxyz"))
# 固定轴欧拉角轴角
print(tfs.euler.euler2axangle(0,0,0,"sxyz"))
# 轴角转固定轴欧拉角
print(tfs.euler.axangle2euler([1,0,0],0.5,"sxyz"))

[-1.0000000e+00  1.2246468e-16  0.0000000e+00 -0.0000000e+00]
[1. 0. 0. 0.]
(0.0, -0.0, 0.0)
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
(0.0, -0.0, 0.0)


In [6]:
R = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
T = np.array([1, 0, 1])
np.vstack((np.hstack((R, T.reshape(3, 1))), [0, 0, 0, 1]))

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [7]:
tfs.affines.compose(T,R,[1,1,1])

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [8]:
R = tfs.quaternions.quat2mat([1, 0, 0, 0])
tfs.affines.compose(T, R, [1, 1, 1])

array([[1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [ ]:
T_BC = tfs.affines.compose([0,0,3],tfs.euler.euler2mat(math.pi,0,0),[1,1,1])
# given a coordinate in space B, multiple to get the coordinate in space C